export const makeUnit = (team: string, kind?: string) => ({
  type: 'unit',
  kind: kind,
  id: team,
  aspects: {
    team: { type: 'team', value: team },
  },
});

export const initialUnits = {
  '0.5.-5': makeUnit('team1', 'bishop'),
  '0.4.-4': makeUnit('team1', 'bishop'),
  '0.3.-3': makeUnit('team1', 'bishop'),
  '-1.5.-4': makeUnit('team1', 'queen'),
  '1.4.-5': makeUnit('team1', 'king'),
  '-2.5.-3': makeUnit('team1', 'knight'),
  '2.3.-5': makeUnit('team1', 'knight'),
  '-3.5.-2': makeUnit('team1', 'rook'),
  '3.2.-5': makeUnit('team1', 'rook'),
  '-4.5.-1': makeUnit('team1', 'pawn'),
  '-3.4.-1': makeUnit('team1', 'pawn'),
  '-2.3.-1': makeUnit('team1', 'pawn'),
  '-1.2.-1': makeUnit('team1', 'pawn'),
  '0.1.-1': makeUnit('team1', 'pawn'),
  '1.1.-2': makeUnit('team1', 'pawn'),
  '2.1.-3': makeUnit('team1', 'pawn'),
  '3.1.-4': makeUnit('team1', 'pawn'),
  '4.1.-5': makeUnit('team1', 'pawn'),
  '0.-5.5': makeUnit('team2', 'bishop'),
  '0.-4.4': makeUnit('team2', 'bishop'),
  '0.-3.3': makeUnit('team2', 'bishop'),
  '-1.-4.5': makeUnit('team2', 'queen'),
  '1.-5.4': makeUnit('team2', 'king'),
  '-2.-3.5': makeUnit('team2', 'knight'),
  '2.-5.3': makeUnit('team2', 'knight'),
  '-3.-2.5': makeUnit('team2', 'rook'),
  '3.-5.2': makeUnit('team2', 'rook'),
  '-4.-1.5': makeUnit('team2', 'pawn'),
  '-3.-1.4': makeUnit('team2', 'pawn'),
  '-2.-1.3': makeUnit('team2', 'pawn'),
  '-1.-1.2': makeUnit('team2', 'pawn'),
  '0.-1.1': makeUnit('team2', 'pawn'),
  '1.-2.1': makeUnit('team2', 'pawn'),
  '2.-3.1': makeUnit('team2', 'pawn'),
  '3.-4.1': makeUnit('team2', 'pawn'),
  '4.-5.1': makeUnit('team2', 'pawn'),
};
