import { makeSwordsman } from './swordsman';

export default {
  '-7.0.7': {
    type: 'hex',
    key: '-7.0.7',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -7, r: 0, s: 7 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-7.1.6': {
    type: 'hex',
    key: '-7.1.6',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -7, r: 1, s: 6 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-7.2.5': {
    type: 'hex',
    key: '-7.2.5',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -7, r: 2, s: 5 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-7.3.4': {
    type: 'hex',
    key: '-7.3.4',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -7, r: 3, s: 4 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-7.4.3': {
    type: 'hex',
    key: '-7.4.3',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -7, r: 4, s: 3 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-7.5.2': {
    type: 'hex',
    key: '-7.5.2',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -7, r: 5, s: 2 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-7.6.1': {
    type: 'hex',
    key: '-7.6.1',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -7, r: 6, s: 1 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-7.7.0': {
    type: 'hex',
    key: '-7.7.0',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -7, r: 7, s: 0 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-6.-1.7': {
    type: 'hex',
    key: '-6.-1.7',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -6, r: -1, s: 7 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-6.0.6': {
    type: 'hex',
    key: '-6.0.6',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -6, r: 0, s: 6 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-6.1.5': {
    type: 'hex',
    key: '-6.1.5',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -6, r: 1, s: 5 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-6.2.4': {
    type: 'hex',
    key: '-6.2.4',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -6, r: 2, s: 4 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-6.3.3': {
    type: 'hex',
    key: '-6.3.3',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -6, r: 3, s: 3 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-6.4.2': {
    type: 'hex',
    key: '-6.4.2',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -6, r: 4, s: 2 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-6.5.1': {
    type: 'hex',
    key: '-6.5.1',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -6, r: 5, s: 1 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-6.6.0': {
    type: 'hex',
    key: '-6.6.0',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -6, r: 6, s: 0 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-6.7.-1': {
    type: 'hex',
    key: '-6.7.-1',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -6, r: 7, s: -1 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-5.-2.7': {
    type: 'hex',
    key: '-5.-2.7',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -5, r: -2, s: 7 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-5.-1.6': {
    type: 'hex',
    key: '-5.-1.6',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -5, r: -1, s: 6 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-5.0.5': {
    type: 'hex',
    key: '-5.0.5',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -5, r: 0, s: 5 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-5.1.4': {
    type: 'hex',
    key: '-5.1.4',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -5, r: 1, s: 4 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-5.2.3': {
    type: 'hex',
    key: '-5.2.3',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -5, r: 2, s: 3 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-5.3.2': {
    type: 'hex',
    key: '-5.3.2',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -5, r: 3, s: 2 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-5.4.1': {
    type: 'hex',
    key: '-5.4.1',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -5, r: 4, s: 1 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-5.5.0': {
    type: 'hex',
    key: '-5.5.0',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -5, r: 5, s: 0 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-5.6.-1': {
    type: 'hex',
    key: '-5.6.-1',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -5, r: 6, s: -1 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-5.7.-2': {
    type: 'hex',
    key: '-5.7.-2',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -5, r: 7, s: -2 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-4.-3.7': {
    type: 'hex',
    key: '-4.-3.7',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -4, r: -3, s: 7 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-4.-2.6': {
    type: 'hex',
    key: '-4.-2.6',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -4, r: -2, s: 6 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-4.-1.5': {
    type: 'hex',
    key: '-4.-1.5',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -4, r: -1, s: 5 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-4.0.4': {
    type: 'hex',
    key: '-4.0.4',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -4, r: 0, s: 4 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-4.2.2': {
    type: 'hex',
    key: '-4.2.2',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -4, r: 2, s: 2 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-4.3.1': {
    type: 'hex',
    key: '-4.3.1',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -4, r: 3, s: 1 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-4.4.0': {
    type: 'hex',
    key: '-4.4.0',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -4, r: 4, s: 0 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-4.5.-1': {
    type: 'hex',
    key: '-4.5.-1',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -4, r: 5, s: -1 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-4.6.-2': {
    type: 'hex',
    key: '-4.6.-2',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -4, r: 6, s: -2 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-4.7.-3': {
    type: 'hex',
    key: '-4.7.-3',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -4, r: 7, s: -3 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-3.-4.7': {
    type: 'hex',
    key: '-3.-4.7',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -3, r: -4, s: 7 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-3.-3.6': {
    type: 'hex',
    key: '-3.-3.6',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -3, r: -3, s: 6 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-3.-2.5': {
    type: 'hex',
    key: '-3.-2.5',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -3, r: -2, s: 5 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-3.-1.4': {
    type: 'hex',
    key: '-3.-1.4',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -3, r: -1, s: 4 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-3.1.2': {
    type: 'hex',
    key: '-3.1.2',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -3, r: 1, s: 2 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-3.2.1': {
    type: 'hex',
    key: '-3.2.1',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -3, r: 2, s: 1 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-3.3.0': {
    type: 'hex',
    key: '-3.3.0',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -3, r: 3, s: 0 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-3.4.-1': {
    type: 'hex',
    key: '-3.4.-1',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -3, r: 4, s: -1 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-3.5.-2': {
    type: 'hex',
    key: '-3.5.-2',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -3, r: 5, s: -2 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-3.6.-3': {
    type: 'hex',
    key: '-3.6.-3',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -3, r: 6, s: -3 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-3.7.-4': {
    type: 'hex',
    key: '-3.7.-4',
    kind: 'hex',
    aspects: {},
    coordinates: { q: -3, r: 7, s: -4 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-2.-5.7': {
    type: 'hex',
    key: '-2.-5.7',
    kind: 'river',
    aspects: {},
    coordinates: { q: -2, r: -5, s: 7 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-2.-4.6': {
    type: 'hex',
    key: '-2.-4.6',
    kind: 'river',
    aspects: {},
    coordinates: { q: -2, r: -4, s: 6 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-2.-3.5': {
    type: 'hex',
    key: '-2.-3.5',
    kind: 'river',
    aspects: {},
    coordinates: { q: -2, r: -3, s: 5 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-2.-2.4': {
    type: 'hex',
    key: '-2.-2.4',
    kind: 'river',
    aspects: {},
    coordinates: { q: -2, r: -2, s: 4 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-2.0.2': {
    type: 'hex',
    key: '-2.0.2',
    kind: 'river',
    aspects: {},
    coordinates: { q: -2, r: 0, s: 2 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-2.1.1': {
    type: 'hex',
    key: '-2.1.1',
    kind: 'river',
    aspects: {},
    coordinates: { q: -2, r: 1, s: 1 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-2.2.0': {
    type: 'hex',
    key: '-2.2.0',
    kind: 'river',
    aspects: {},
    coordinates: { q: -2, r: 2, s: 0 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-2.3.-1': {
    type: 'hex',
    key: '-2.3.-1',
    kind: 'river',
    aspects: {},
    coordinates: { q: -2, r: 3, s: -1 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-2.4.-2': {
    type: 'hex',
    key: '-2.4.-2',
    kind: 'river',
    aspects: {},
    coordinates: { q: -2, r: 4, s: -2 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-2.5.-3': {
    type: 'hex',
    key: '-2.5.-3',
    kind: 'river',
    aspects: {},
    coordinates: { q: -2, r: 5, s: -3 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-2.6.-4': {
    type: 'hex',
    key: '-2.6.-4',
    kind: 'river',
    aspects: {},
    coordinates: { q: -2, r: 6, s: -4 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-2.7.-5': {
    type: 'hex',
    key: '-2.7.-5',
    kind: 'river',
    aspects: {},
    coordinates: { q: -2, r: 7, s: -5 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-1.-6.7': {
    type: 'hex',
    key: '-1.-6.7',
    kind: 'hex',
    aspects: { hot: { type: 'hot' } },
    coordinates: { q: -1, r: -6, s: 7 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-1.-5.6': {
    type: 'hex',
    key: '-1.-5.6',
    kind: 'hex',
    aspects: { hot: { type: 'hot' } },
    coordinates: { q: -1, r: -5, s: 6 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-1.-4.5': {
    type: 'hex',
    key: '-1.-4.5',
    kind: 'hex',
    aspects: { hot: { type: 'hot' } },
    coordinates: { q: -1, r: -4, s: 5 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-1.-3.4': {
    type: 'hex',
    key: '-1.-3.4',
    kind: 'hex',
    aspects: { hot: { type: 'hot' } },
    coordinates: { q: -1, r: -3, s: 4 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-1.-2.3': {
    type: 'hex',
    key: '-1.-2.3',
    kind: 'hex',
    aspects: { hot: { type: 'hot' } },
    coordinates: { q: -1, r: -2, s: 3 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-1.-1.2': {
    type: 'hex',
    key: '-1.-1.2',
    kind: 'hex',
    aspects: { hot: { type: 'hot' } },
    coordinates: { q: -1, r: -1, s: 2 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-1.0.1': {
    type: 'hex',
    key: '-1.0.1',
    kind: 'hex',
    aspects: { hot: { type: 'hot' } },
    coordinates: { q: -1, r: 0, s: 1 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-1.1.0': {
    type: 'hex',
    key: '-1.1.0',
    kind: 'hex',
    aspects: { hot: { type: 'hot' } },
    coordinates: { q: -1, r: 1, s: 0 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-1.2.-1': {
    type: 'hex',
    key: '-1.2.-1',
    kind: 'hex',
    aspects: { hot: { type: 'hot' } },
    coordinates: { q: -1, r: 2, s: -1 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-1.3.-2': {
    type: 'hex',
    key: '-1.3.-2',
    kind: 'hex',
    aspects: { hot: { type: 'hot' } },
    coordinates: { q: -1, r: 3, s: -2 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-1.4.-3': {
    type: 'hex',
    key: '-1.4.-3',
    kind: 'hex',
    aspects: { hot: { type: 'hot' } },
    coordinates: { q: -1, r: 4, s: -3 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-1.5.-4': {
    type: 'hex',
    key: '-1.5.-4',
    kind: 'hex',
    aspects: { hot: { type: 'hot' } },
    coordinates: { q: -1, r: 5, s: -4 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-1.6.-5': {
    type: 'hex',
    key: '-1.6.-5',
    kind: 'hex',
    aspects: { hot: { type: 'hot' } },
    coordinates: { q: -1, r: 6, s: -5 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '-1.7.-6': {
    type: 'hex',
    key: '-1.7.-6',
    kind: 'hex',
    aspects: { hot: { type: 'hot' } },
    coordinates: { q: -1, r: 7, s: -6 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '0.-7.7': {
    type: 'hex',
    key: '0.-7.7',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 0, r: -7, s: 7 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '0.-6.6': {
    type: 'hex',
    key: '0.-6.6',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 0, r: -6, s: 6 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '0.-5.5': {
    type: 'hex',
    key: '0.-5.5',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 0, r: -5, s: 5 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '0.-4.4': {
    type: 'hex',
    key: '0.-4.4',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 0, r: -4, s: 4 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '0.-3.3': {
    type: 'hex',
    key: '0.-3.3',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 0, r: -3, s: 3 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '0.-2.2': {
    type: 'hex',
    key: '0.-2.2',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 0, r: -2, s: 2 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '0.-1.1': {
    type: 'hex',
    key: '0.-1.1',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 0, r: -1, s: 1 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '0.0.0': {
    type: 'hex',
    key: '0.0.0',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 0, r: 0, s: 0 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '0.1.-1': {
    type: 'hex',
    key: '0.1.-1',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 0, r: 1, s: -1 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '0.2.-2': {
    type: 'hex',
    key: '0.2.-2',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 0, r: 2, s: -2 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '0.3.-3': {
    type: 'hex',
    key: '0.3.-3',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 0, r: 3, s: -3 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '0.4.-4': {
    type: 'hex',
    key: '0.4.-4',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 0, r: 4, s: -4 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '0.5.-5': {
    type: 'hex',
    key: '0.5.-5',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 0, r: 5, s: -5 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '0.6.-6': {
    type: 'hex',
    key: '0.6.-6',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 0, r: 6, s: -6 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '0.7.-7': {
    type: 'hex',
    key: '0.7.-7',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 0, r: 7, s: -7 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '1.-7.6': {
    type: 'hex',
    key: '1.-7.6',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 1, r: -7, s: 6 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '1.-6.5': {
    type: 'hex',
    key: '1.-6.5',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 1, r: -6, s: 5 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '1.-5.4': {
    type: 'hex',
    key: '1.-5.4',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 1, r: -5, s: 4 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '1.-4.3': {
    type: 'hex',
    key: '1.-4.3',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 1, r: -4, s: 3 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '1.-3.2': {
    type: 'hex',
    key: '1.-3.2',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 1, r: -3, s: 2 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '1.-2.1': {
    type: 'hex',
    key: '1.-2.1',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 1, r: -2, s: 1 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '1.-1.0': {
    type: 'hex',
    key: '1.-1.0',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 1, r: -1, s: 0 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '1.0.-1': {
    type: 'hex',
    key: '1.0.-1',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 1, r: 0, s: -1 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '1.1.-2': {
    type: 'hex',
    key: '1.1.-2',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 1, r: 1, s: -2 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '1.2.-3': {
    type: 'hex',
    key: '1.2.-3',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 1, r: 2, s: -3 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '1.3.-4': {
    type: 'hex',
    key: '1.3.-4',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 1, r: 3, s: -4 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '1.4.-5': {
    type: 'hex',
    key: '1.4.-5',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 1, r: 4, s: -5 },
    isSelected: false,
    contains: { unit: makeSwordsman('team2') },
    preview: {},
  },
  '1.5.-6': {
    type: 'hex',
    key: '1.5.-6',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 1, r: 5, s: -6 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '1.6.-7': {
    type: 'hex',
    key: '1.6.-7',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 1, r: 6, s: -7 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '2.-7.5': {
    type: 'hex',
    key: '2.-7.5',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 2, r: -7, s: 5 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '2.-6.4': {
    type: 'hex',
    key: '2.-6.4',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 2, r: -6, s: 4 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '2.-5.3': {
    type: 'hex',
    key: '2.-5.3',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 2, r: -5, s: 3 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '2.-4.2': {
    type: 'hex',
    key: '2.-4.2',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 2, r: -4, s: 2 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '2.-3.1': {
    type: 'hex',
    key: '2.-3.1',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 2, r: -3, s: 1 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '2.-2.0': {
    type: 'hex',
    key: '2.-2.0',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 2, r: -2, s: 0 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '2.-1.-1': {
    type: 'hex',
    key: '2.-1.-1',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 2, r: -1, s: -1 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '2.0.-2': {
    type: 'hex',
    key: '2.0.-2',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 2, r: 0, s: -2 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '2.1.-3': {
    type: 'hex',
    key: '2.1.-3',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 2, r: 1, s: -3 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '2.2.-4': {
    type: 'hex',
    key: '2.2.-4',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 2, r: 2, s: -4 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '2.3.-5': {
    type: 'hex',
    key: '2.3.-5',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 2, r: 3, s: -5 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '2.4.-6': {
    type: 'hex',
    key: '2.4.-6',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 2, r: 4, s: -6 },
    isSelected: false,
    contains: { unit: makeSwordsman('team1') },
    preview: {},
  },
  '2.5.-7': {
    type: 'hex',
    key: '2.5.-7',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 2, r: 5, s: -7 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '3.-7.4': {
    type: 'hex',
    key: '3.-7.4',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 3, r: -7, s: 4 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '3.-6.3': {
    type: 'hex',
    key: '3.-6.3',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 3, r: -6, s: 3 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '3.-5.2': {
    type: 'hex',
    key: '3.-5.2',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 3, r: -5, s: 2 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '3.-4.1': {
    type: 'hex',
    key: '3.-4.1',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 3, r: -4, s: 1 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '3.-3.0': {
    type: 'hex',
    key: '3.-3.0',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 3, r: -3, s: 0 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '3.-2.-1': {
    type: 'hex',
    key: '3.-2.-1',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 3, r: -2, s: -1 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '3.-1.-2': {
    type: 'hex',
    key: '3.-1.-2',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 3, r: -1, s: -2 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '3.0.-3': {
    type: 'hex',
    key: '3.0.-3',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 3, r: 0, s: -3 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '3.1.-4': {
    type: 'hex',
    key: '3.1.-4',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 3, r: 1, s: -4 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '3.2.-5': {
    type: 'hex',
    key: '3.2.-5',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 3, r: 2, s: -5 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '3.3.-6': {
    type: 'hex',
    key: '3.3.-6',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 3, r: 3, s: -6 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '3.4.-7': {
    type: 'hex',
    key: '3.4.-7',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 3, r: 4, s: -7 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '4.-7.3': {
    type: 'hex',
    key: '4.-7.3',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 4, r: -7, s: 3 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '4.-6.2': {
    type: 'hex',
    key: '4.-6.2',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 4, r: -6, s: 2 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '4.-5.1': {
    type: 'hex',
    key: '4.-5.1',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 4, r: -5, s: 1 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '4.-4.0': {
    type: 'hex',
    key: '4.-4.0',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 4, r: -4, s: 0 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '4.-3.-1': {
    type: 'hex',
    key: '4.-3.-1',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 4, r: -3, s: -1 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '4.-2.-2': {
    type: 'hex',
    key: '4.-2.-2',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 4, r: -2, s: -2 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '4.-1.-3': {
    type: 'hex',
    key: '4.-1.-3',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 4, r: -1, s: -3 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '4.0.-4': {
    type: 'hex',
    key: '4.0.-4',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 4, r: 0, s: -4 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '4.1.-5': {
    type: 'hex',
    key: '4.1.-5',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 4, r: 1, s: -5 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '4.2.-6': {
    type: 'hex',
    key: '4.2.-6',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 4, r: 2, s: -6 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '4.3.-7': {
    type: 'hex',
    key: '4.3.-7',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 4, r: 3, s: -7 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '5.-7.2': {
    type: 'hex',
    key: '5.-7.2',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 5, r: -7, s: 2 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '5.-6.1': {
    type: 'hex',
    key: '5.-6.1',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 5, r: -6, s: 1 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '5.-5.0': {
    type: 'hex',
    key: '5.-5.0',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 5, r: -5, s: 0 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '5.-4.-1': {
    type: 'hex',
    key: '5.-4.-1',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 5, r: -4, s: -1 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '5.-3.-2': {
    type: 'hex',
    key: '5.-3.-2',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 5, r: -3, s: -2 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '5.-2.-3': {
    type: 'hex',
    key: '5.-2.-3',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 5, r: -2, s: -3 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '5.-1.-4': {
    type: 'hex',
    key: '5.-1.-4',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 5, r: -1, s: -4 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '5.0.-5': {
    type: 'hex',
    key: '5.0.-5',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 5, r: 0, s: -5 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '5.1.-6': {
    type: 'hex',
    key: '5.1.-6',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 5, r: 1, s: -6 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '5.2.-7': {
    type: 'hex',
    key: '5.2.-7',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 5, r: 2, s: -7 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '6.-7.1': {
    type: 'hex',
    key: '6.-7.1',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 6, r: -7, s: 1 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '6.-6.0': {
    type: 'hex',
    key: '6.-6.0',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 6, r: -6, s: 0 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '6.-5.-1': {
    type: 'hex',
    key: '6.-5.-1',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 6, r: -5, s: -1 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '6.-4.-2': {
    type: 'hex',
    key: '6.-4.-2',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 6, r: -4, s: -2 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '6.-3.-3': {
    type: 'hex',
    key: '6.-3.-3',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 6, r: -3, s: -3 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '6.-2.-4': {
    type: 'hex',
    key: '6.-2.-4',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 6, r: -2, s: -4 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '6.-1.-5': {
    type: 'hex',
    key: '6.-1.-5',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 6, r: -1, s: -5 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '6.0.-6': {
    type: 'hex',
    key: '6.0.-6',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 6, r: 0, s: -6 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '6.1.-7': {
    type: 'hex',
    key: '6.1.-7',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 6, r: 1, s: -7 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '7.-7.0': {
    type: 'hex',
    key: '7.-7.0',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 7, r: -7, s: 0 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '7.-6.-1': {
    type: 'hex',
    key: '7.-6.-1',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 7, r: -6, s: -1 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '7.-5.-2': {
    type: 'hex',
    key: '7.-5.-2',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 7, r: -5, s: -2 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '7.-4.-3': {
    type: 'hex',
    key: '7.-4.-3',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 7, r: -4, s: -3 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '7.-3.-4': {
    type: 'hex',
    key: '7.-3.-4',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 7, r: -3, s: -4 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '7.-2.-5': {
    type: 'hex',
    key: '7.-2.-5',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 7, r: -2, s: -5 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '7.-1.-6': {
    type: 'hex',
    key: '7.-1.-6',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 7, r: -1, s: -6 },
    isSelected: false,
    contains: {},
    preview: {},
  },
  '7.0.-7': {
    type: 'hex',
    key: '7.0.-7',
    kind: 'hex',
    aspects: {},
    coordinates: { q: 7, r: 0, s: -7 },
    isSelected: false,
    contains: {},
    preview: {},
  },
};
